feat(event): event system intro, close #8
TeamCovertDragon/Sputnik pull request #24
Opened 2020-05-05 05:58 UTC by 3TUSK

## Synopsis / 简介

事件系统简介。

## Description / 详细说明

几段话概括事件系统。Close #8。

## Justification / 理由

基于 Forge 开发一个 Minecraft Mod 肯定要用到事件系统。

## Remarks / 备注

> 是谁在给我挖坑？！

2020-05-05 14:18 UTC, SeraphJACK requested changes

2020-05-05 14:18 UTC, SeraphJACK commented on docs/event/README.md
> +简单来说，事件是某种事物从无到有的过程。
从无到有？？

2020-05-05 14:18 UTC, SeraphJACK commented on docs/event/README.md
> +订阅事件的方法有时候也会叫“回调”（Callback）。
callback 特指调用某个函数的时候参数传入另一个函数，这里应该不适用

ref: https://zh.wikipedia.org/wiki/%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0

2020-05-05 14:18 UTC, SeraphJACK commented on docs/event/README.md
> +
是不是可以补充说明一下事件的取消

2020-05-05 14:32 UTC, Yesterday17 requested changes

2020-05-05 14:32 UTC, Yesterday17 commented on docs/event/README.md
> +Minecraft 本身没有完整的事件系统，但是 Forge 的目标之一是让“不同的 Mod 能共同工作”。
“Minecraft 本身没有完整的事件系统”和“Forge 的目标”没有转折关系，请核（不是

2020-05-05 14:32 UTC, Yesterday17 commented on docs/event/README.md
> +你只要正确订阅事件，就基本不用担心自己的 Mod 会和别的 Mod 冲突了。
不正确订阅事件也不会导致自己的 Mod 和别的 Mod 冲突（

2020-05-05 14:32 UTC, Yesterday17 commented on docs/event/why-my-events-do-not-work.md
> +或者，如果你用 `@Mod.EventBusSubscriber`：
```diff
- 或者，如果你用 `@Mod.EventBusSubscriber`：
+ 或者，如果你用 `@Mod.EventBusSubscriber`，那你的代码应该是这样的：
```

2020-05-05 14:32 UTC, Yesterday17 commented on docs/event/why-my-events-do-not-work.md
> +|你是这么注册的……|那你应该这样订阅……|方法的访问级别……
```diff
-|你是这么注册的……|那你应该这样订阅……|方法的访问级别……
+|如果你是这么注册的……|那你应该这样订阅……|方法的访问级别……
```

2020-05-05 14:32 UTC, Yesterday17 commented on docs/event/why-my-events-do-not-work.md
> +一般来说，需要走 Mod 总线的事件都应当在 Mod 主类的构造器里就订阅完成：
此处是否需要再起一个 `h2`？

2020-05-05 16:38 UTC, 3TUSK commented on docs/event/README.md
> +简单来说，事件是某种事物从无到有的过程。
在经过~~痛苦的~~思考和请教别人之后得出的结论。

2020-05-05 16:39 UTC, 3TUSK commented on docs/event/README.md
> +订阅事件的方法有时候也会叫“回调”（Callback）。
_这玩意居然有定义的_

2020-05-05 16:46 UTC, 3TUSK commented on docs/event/README.md
> +Minecraft 本身没有完整的事件系统，但是 Forge 的目标之一是让“不同的 Mod 能共同工作”。
“Minecraft 本身没有完整的事件系统，所以我们不能轻易干涉原版逻辑。然而，当有好几个 Mod 同时试图修改同一处逻辑的时候，比如玩家受到伤害时提供不同程度的伤害减免，此时我们需要一套能让这些 Mod 同时工作的机制。为此，Forge 引入了一套事件总线。”

大概像这样？

2020-05-05 16:46 UTC, 3TUSK commented on docs/event/README.md
> +
_确实好像跳得太快了点_

2020-05-05 16:47 UTC, 3TUSK commented on docs/event/why-my-events-do-not-work.md
> +一般来说，需要走 Mod 总线的事件都应当在 Mod 主类的构造器里就订阅完成：
或者 h3。其实某种意义上这里的上下文是连贯的。

2020-05-05 16:59 UTC, Yesterday17 commented on docs/event/README.md
> +Minecraft 本身没有完整的事件系统，但是 Forge 的目标之一是让“不同的 Mod 能共同工作”。
“Minecraft 本身没有完整的事件系统，所以我们不能轻易干涉原版逻辑。而修改原版逻辑又确实 是 Mod 开发过程中所需要用到的，比如不同 Mod 在玩家受到伤害时可能会想要提供不同程度的伤害减免。因此，我们需要一套能让好几个 Mod 同时需要对同一处逻辑进行修改，并且又能够同时工作的机制。为此，Forge 引入了一套事件总线。”

大概这样？

2020-05-06 15:36 UTC, SeraphJACK commented on docs/event/README.md
> +简单来说，事件是某种事物从无到有的过程。
请解释

2020-05-06 16:49 UTC, 3TUSK commented on docs/event/README.md
> +简单来说，事件是某种事物从无到有的过程。
简单来说，事件就是事物出现的*过程*。所以是”从无到有“。

------

昨天讨论的结果给出了“发生”、“出现“、”被创建“等可能的描述。

2020-05-07 13:43 UTC, SeraphJACK commented on docs/event/README.md
> +简单来说，事件是某种事物从无到有的过程。
1. 我不太理解
2. 我认为这个解释不利于新人理解

2020-05-07 16:48 UTC, 3TUSK commented on docs/event/README.md
> +简单来说，事件是某种事物从无到有的过程。
那我需要一个新的解释……

2020-05-24 02:20 UTC, 3TUSK commented on docs/event/README.md
> +简单来说，事件是某种事物从无到有的过程。
先把目前的解释默认折叠了，等我们以后找到更好的解释的时候再回头来看。

2020-05-24 02:22 UTC, 3TUSK commented
先合并了，至于“什么是事件”我们可以以后找到更好的解释后再来看。目前的解释已经折叠。

2020-05-24 02:22 UTC, merged